package com.twd.chitboyapp.spsskl.enums;

public enum DataSetter {
    VILLAGE, HANGAM, VARIETY, IRRIGATION, LANETYPE, HARVESTTYPE, WATERCOND, BANK, BANKBRANCH, REASON, PLOTNO, CANETYPE, VEHICALTYPE, WIREROPE, FRONTTRAILER, BACKTRAILER, REMARK, BULLUCKCART, FACTORY, HEAD, EVEN, ODD, FOOT, DO, SALETYPE, YARD, VEHICALGROUP, LOTNO, STATUS, ROLE, USER, SHIFT, PUMP, PRODUCT, CUSTOMERTYPE, SECTION
}
